/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.req.view;

import br.com.req.dao.FuncionarioDao;
import br.com.req.model.Funcionario;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giovane Oliveira
 */
public class ReqFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form ReqFornecedores
     */
    public ReqFornecedores() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/req/images/logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtpesquisarFornecedor = new javax.swing.JTextField();
        btnPesquisarFornecedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedores = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Fornecedor:");

        txtpesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisarFornecedorActionPerformed(evt);
            }
        });
        txtpesquisarFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisarFornecedorKeyPressed(evt);
            }
        });

        btnPesquisarFornecedor.setText("Pesquisar");
        btnPesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFornecedorActionPerformed(evt);
            }
        });

        TabelaFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaFornecedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisarFornecedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnPesquisarFornecedor))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisarFornecedorActionPerformed

    }//GEN-LAST:event_txtpesquisarFornecedorActionPerformed

    private void txtpesquisarFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisarFornecedorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            FuncionarioDao dao =  new FuncionarioDao();
            List<Funcionario> lista = dao.listarFornecedoresPorNome("%" + txtpesquisarFornecedor.getText() + "%");
            if(lista.isEmpty()){

                listar();

            }
            DefaultTableModel dados = (DefaultTableModel) TabelaFornecedores.getModel();
            dados.setNumRows(0);
            for(Funcionario c : lista){

                dados.addRow(new Object[]{
                    c.getCodigo(),
                    c.getNome()

                });
            }

        }

    }//GEN-LAST:event_txtpesquisarFornecedorKeyPressed

    private void btnPesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFornecedorActionPerformed
        FuncionarioDao dao =  new FuncionarioDao();
        List<Funcionario> lista = dao.listarFornecedoresPorNome("%" + txtpesquisarFornecedor.getText() + "%");
        if(lista.isEmpty()){

            listar();

        }
        DefaultTableModel dados = (DefaultTableModel) TabelaFornecedores.getModel();
        dados.setNumRows(0);
        for(Funcionario c : lista){

            dados.addRow(new Object[]{
                c.getCodigo(),
                c.getNome()

            });
        }

    }//GEN-LAST:event_btnPesquisarFornecedorActionPerformed

    
       public void listar() {

        // TODO add your handling code here:
        FuncionarioDao dao = new FuncionarioDao();
        List<Funcionario> lista = dao.ListarFornecedor();
        DefaultTableModel dados = (DefaultTableModel) TabelaFornecedores.getModel();
        dados.setNumRows(0);
        for (Funcionario c : lista) {

            dados.addRow(new Object[]{
                c.getCodigo(),
                c.getNome()

            });
        }

    }
    
    
    
    private void TabelaFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFornecedoresMouseClicked
        // TODO add your handling code here:
        ReqCompras req = ReqCompras.x;

        req.fornecedor.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 0).toString()); 
        req.lblFornecedor.setText(TabelaFornecedores.getValueAt(TabelaFornecedores.getSelectedRow(), 1).toString());
        req.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_TabelaFornecedoresMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReqFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReqFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReqFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReqFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReqFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFornecedores;
    private javax.swing.JButton btnPesquisarFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtpesquisarFornecedor;
    // End of variables declaration//GEN-END:variables
}
